  Q1.

"=="checks if true values are equal while "is" checks if the two variables refer to the same object in memory  

for eg: a = [1, 2] and b = [1, 2] can give a == b as True, but a is b as False because they are separate list objects.

Q2.

mutable: list, set, dict
immutable: tuple, str, int, float, bool, frozenset

immutability matters because an immutable vvalue cannot be changed accidentally after it is created making the code more predictable

Q3.
false

In [ ]:
print(0.1 + 0.2 == 0.3)

False


this happens because python stores decimal numbers in binary so numbers like 0.1 and 0.2 arent stored exactly. because of this a small rounding difference happens and the result isnt exactly 0.3.

Q4.
RGB color values(each value represents a fixed color so it doesnt need to be changed)
cordinates(cordinates usually shouldnt eb changed after creation so a tuple protects it from accidental modification)
months of the year (names and order of the months are fixed)

Q5.
(without hash) a  dictionary can quickly find a value by going directly to its location so lookup is O(1) on average

(with hash) a dictionary uses a hash to quickly find where a key is stored giving O(1) average lookup

Q6.
data type:range() returns a range of integers while numpy.arange() can also use floats
library:range() is built into Python while numpy.arange() requires NumPy
output:range() gives a range object while numpy.arange() gives a NumPy array


Q7.
append()= adds one thing at the end

extend()= adds multiple things

insert()= adds one thing at a chosen position


Q8.
a gets the first value, c gets the last value, and b gets all the values in between. so a = 10, b = [20, 30, 40], and c = 50.
For [10, 20], a = 10, b is empty, and c = 20. For [10], it gives an error because there is only one value.


Q9.
/ → normal division → -7 / 2 = -3.5
// → floor division → -7 // 2 = -4
% → gives remainder → -7 % 2 = 1
** → power → -7 ** 2 = 49

Q10. NumPy keeps the numbers close together in memory so they can be accessed faster.
it can do many calculations together instead of doing them one by one.
NumPy uses faster code made specially for doing calculations.

Q11.
predicted output:
[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]

In [3]:
matrix1 = [[0] * 3 for _ in range(3)]
matrix2 = [[0] * 3] * 3

matrix1[0][0] = 99
matrix2[0][0] = 99

print(matrix1)
print(matrix2)

[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]


the first one has 3 separate lists so changing one row doesnt affect the others. the second one uses the same list 3 times so changing one row changes all of them.

Q12.
Predicted output:

x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]

In [4]:
x = [1, 2, 3]
y = x

x = x + [4]

print("x =", x)
print("y =", y)

a = [1, 2, 3]
b = a

a += [4]

print("a =", a)
print("b =", b)

x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]


x = x + [4] makes a new list and puts it in x, so y stays the same. but a += [4] changes the original list, and b is also connected to that same list so b changes too.

Q13.
predicted output

NameError: name 'j' is not defined

In [5]:
for i in range(5):
    pass

print(i)

for j in range(0):
    pass

print(j)

4


NameError: name 'j' is not defined

the value of i after the loop is 4

range(5) goes from 0 to 4. The loop ends after i becomes 4 so the value of i after the loop is 4.

Q14.
predicted output:
1020
30
101010
333

In [6]:
print("10" + 20)          # TypeError
print(int("10") + 20)     # 30

TypeError: can only concatenate str (not "int") to str

"10" + "20" gives 1020 because both are strings so they get joined together.
10 + 20 gives 30 because they are numbers.
"10" * 3 gives 101010 because the string is repeated 3 times. 10 * "3" gives 3333333333 because "3" is repeated 10 times.
"10" + 20 gives an error because one is a string and the other is a number. int("10") + 20 gives 30 because int() changes "10" into a number.

Q15.
predicted output
0
5
hello
0
10
default
[0]

In [7]:
print(0 or 5)
print(5 or 0)
print(None or "hello")
print(0 and 5)
print(5 and 10)
print([] or "default")
print([0] or "default")  # careful!

5
5
hello
0
10
default
[0]


python stops checking as soon as it already knows the answer when using "and" or "or"

Q16.


using arithmatic

In [8]:
a = 10
b = 20

a = a + b
b = a - b
a = a - b

print("a =", a)
print("b =", b)

a = 20
b = 10


using XOR

In [9]:
a = 10
b = 20

a = a ^ b
b = a ^ b
a = a ^ b

print("a =", a)
print("b =", b)

a = 20
b = 10


using tuple unpacking

In [10]:
a = 10
b = 20

a, b = b, a

print("a =", a)
print("b =", b)

a = 20
b = 10


tuple unpacking is the most pythonic.

Q17

In [ ]:
price = float(input("Enter item price: "))
quantity = int(input("Enter quantity: "))

subtotal = price * quantity
gst = subtotal * 0.18

if subtotal < 500:
    delivery = 40
else:
    delivery = 0

total = subtotal + gst + delivery

print("Subtotal: Rs.", round(subtotal, 2))
print("GST (18%): Rs.", round(gst, 2))
print("Delivery: Rs.", round(delivery, 2))
print("------------------------")
print("Total: Rs.", round(total, 2))

Enter item price: 23
Enter quantity: 2
Subtotal: Rs. 46.0
GST (18%): Rs. 8.28
Delivery: Rs. 40
------------------------
Total: Rs. 94.28


first it finds the total price by multiplying the price by the quantity. then it adds 18% GST. if the total is less than ₹500 it adds ₹40 for delivery. if it is ₹500 or more there is no delivery charge.

Q18.

In [14]:
temperature = float(input("Enter temperature: "))
unit = input("Enter unit (C or F): ")

if unit == "C":
    result = (temperature * 9/5) + 32
    print("Temperature in Fahrenheit:", round(result, 2))

elif unit == "F":
    result = (temperature - 32) * 5/9
    print("Temperature in Celsius:", round(result, 2))

else:
    print("Invalid unit. Please enter C or F.")

Enter temperature: 32
Enter unit (C or F): C
Temperature in Fahrenheit: 89.6


Q19

In [13]:
number = int(input("Enter a 4-digit number: "))

digit1 = number // 1000
digit2 = (number // 100) % 10
digit3 = (number // 10) % 10
digit4 = number % 10

sum_of_digits = digit1 + digit2 + digit3 + digit4

print("Sum of digits:", sum_of_digits)

Enter a 4-digit number: 4444
Sum of digits: 16


Q20

In [15]:
value = input("Enter something: ")

try:
    value = int(value)
    print(value, "int")

except:
    try:
        value = float(value)
        print(value, "float")

    except:
        print(value, "str")

Enter something: hello
hello str


Q21

In [16]:
income = float(input("Enter your annual income: "))

tax = 0

if income > 1500000:
    tax += (income - 1500000) * 0.30
    income = 1500000

if income > 1200000:
    tax += (income - 1200000) * 0.20
    income = 1200000

if income > 1000000:
    tax += (income - 1000000) * 0.15
    income = 1000000

if income > 700000:
    tax += (income - 700000) * 0.10
    income = 700000

if income > 300000:
    tax += (income - 300000) * 0.05

print("Tax breakdown:")
print("Up to ₹3,00,000: ₹0.00")
print("Total tax: ₹{:.2f}".format(tax))

Enter your annual income: 80000
Tax breakdown:
Up to ₹3,00,000: ₹0.00
Total tax: ₹0.00


Q22

In [17]:
pan = input("Enter PAN number: ")

if len(pan) != 10:
    print("Invalid PAN — length must be 10")

elif not pan[:5].isalpha() or not pan[:5].isupper():
    print("Invalid PAN — first 5 characters must be uppercase letters")

elif not pan[5:9].isdigit():
    print("Invalid PAN — characters 6 to 9 must be digits")

elif not pan[9].isalpha() or not pan[9].isupper():
    print("Invalid PAN — last character must be an uppercase letter")

else:
    print("Valid PAN")

Enter PAN number: ABCDE1234F
Valid PAN


Q23

In [18]:
units = float(input("Enter units consumed: "))

if units <= 50:
    energy_charge = units * 4.10

elif units <= 100:
    energy_charge = (50 * 4.10) + ((units - 50) * 5.55)

elif units <= 200:
    energy_charge = (50 * 4.10) + (50 * 5.55) + ((units - 100) * 7.10)

else:
    energy_charge = (50 * 4.10) + (50 * 5.55) + (100 * 7.10) + ((units - 200) * 8.15)

fixed_charge = 110

government_tax = (energy_charge + fixed_charge) * 0.06

total = energy_charge + fixed_charge + government_tax

print("Energy Charges: ₹{:.2f}".format(energy_charge))
print("Fixed Charge: ₹{:.2f}".format(fixed_charge))
print("Government Tax (6%): ₹{:.2f}".format(government_tax))
print("------------------------")
print("Total Bill: ₹{:.2f}".format(total))

Enter units consumed: 10
Energy Charges: ₹41.00
Fixed Charge: ₹110.00
Government Tax (6%): ₹9.06
------------------------
Total Bill: ₹160.06


Q24

In [19]:
runs = float(input("Enter runs scored: "))
balls = int(input("Enter balls faced: "))

if balls == 0:
    print("Cannot calculate strike rate because balls faced is 0.")

else:
    strike_rate = (runs / balls) * 100

    print("Strike Rate:", strike_rate)

    if strike_rate > 150:
        print("Classification: Explosive (T20 finisher)")

    elif strike_rate > 100:
        print("Classification: Aggressive (Top order T20)")

    elif strike_rate >= 75:
        print("Classification: Steady (ODI anchor)")

    else:
        print("Classification: Defensive (Test match)")

Enter runs scored: 6
Enter balls faced: 5
Strike Rate: 120.0
Classification: Aggressive (Top order T20)


Q25

In [20]:
weight = float(input("Enter weight in kg: "))
height = float(input("Enter height in cm: "))

height_in_meters = height / 100

bmi = weight / (height_in_meters ** 2)

print("BMI:", round(bmi, 2))

if bmi < 18.5:
    print("Category: Underweight")

elif bmi <= 22.9:
    print("Category: Normal")

elif bmi <= 24.9:
    print("Category: Overweight")

elif bmi <= 29.9:
    print("Category: Obese Class I")

else:
    print("Category: Obese Class II")

Enter weight in kg: 56
Enter height in cm: 156
BMI: 23.01
Category: Overweight


Q26

In [21]:
n = int(input("Enter N: "))

for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

Enter N: 2
1 
1 2 


Q27


In [22]:
n = int(input("Enter N: "))

for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

for i in range(n - 1, 0, -1):
    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

Enter N: 4
1 
1 2 1 
1 2 3 2 1 
1 2 3 4 3 2 1 
1 2 3 2 1 
1 2 1 
1 


Q28

In [23]:
n = int(input("Enter N: "))

for i in range(n):
    for j in range(n):
        if i == 0 or i == n - 1 or j == 0 or j == n - 1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

Enter N: 5
* * * * * 
*       * 
*       * 
*       * 
* * * * * 


Q29

In [24]:
for i in range(5):
    number = 1

    for j in range(i + 1):
        print(number, end=" ")

        number = number * (i - j) // (j + 1)

    print()

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 


Q30

In [25]:
n = int(input("Enter N: "))

for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(chr(64 + j), end=" ")
    print()

Enter N: 6
A 
A B 
A B C 
A B C D 
A B C D E 
A B C D E F 


Q31

In [26]:
armstrong_numbers = []

for number in range(1, 10000):
    temp = number
    digits = 0

    while temp > 0:
        digits += 1
        temp = temp // 10

    temp = number
    total = 0

    while temp > 0:
        digit = temp % 10
        total = total + (digit ** digits)
        temp = temp // 10

    if total == number:
        armstrong_numbers.append(number)

print(", ".join(map(str, armstrong_numbers)))
print("Count:", len(armstrong_numbers))

1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474
Count: 16


Q32

In [27]:
n = int(input("Enter N: "))

a = 0
b = 1
total = 0

for i in range(n):
    print(a, end=" ")

    total = total + a

    next_term = a + b
    a = b
    b = next_term

print()
print("SUM:", total)

Enter N: 6
0 1 1 2 3 5 
SUM: 12


Q33

In [28]:
n = int(input("Enter N: "))

is_prime = True

if n < 2:
    is_prime = False
else:
    i = 2

    while i * i <= n:
        if n % i == 0:
            is_prime = False
            break
        i += 1

if is_prime:
    print(n, "is prime")
else:
    print(n, "is not prime")

total = 0

for number in range(2, n + 1):
    prime = True
    i = 2

    while i * i <= number:
        if number % i == 0:
            prime = False
            break
        i += 1

    if prime:
        total = total + number

print("SUM of primes:", total)

Enter N: 7
7 is prime
SUM of primes: 17


Q34

In [29]:
number = int(input("Enter a number: "))

original = number
reverse = 0

if number < 0:
    print("Not a palindrome")
else:
    while number > 0:
        digit = number % 10
        reverse = reverse * 10 + digit
        number = number // 10

    print("Reversed number:", reverse)

    if original == reverse:
        print("Palindrome")
    else:
        print("Not a palindrome")

Enter a number: 6
Reversed number: 6
Palindrome


Q35

In [30]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

x = a
y = b

while y != 0:
    remainder = x % y
    x = y
    y = remainder

hcf = x
lcm = (a * b) // hcf

print("HCF:", hcf)
print("LCM:", lcm)

Enter first number: 6
Enter second number: 7
HCF: 1
LCM: 42


Q36


In [31]:
sentence = input("Enter a sentence: ")

characters = len(sentence)
words = 0
vowels = 0
consonants = 0
digits = 0
spaces = 0
special = 0

for char in sentence:
    if char.isalpha():
        if char.lower() in "aeiou":
            vowels += 1
        else:
            consonants += 1

    elif char.isdigit():
        digits += 1

    elif char == " ":
        spaces += 1

    else:
        special += 1

words = len(sentence.split())

print("Total characters:", characters)
print("Total words:", words)
print("Vowels:", vowels)
print("Consonants:", consonants)
print("Digits:", digits)
print("Spaces:", spaces)
print("Special characters:", special)

Enter a sentence: hello world
Total characters: 11
Total words: 2
Vowels: 3
Consonants: 7
Digits: 0
Spaces: 1
Special characters: 0


Q37

In [35]:
marks = list(map(int, input("Enter 10 marks: ").split()))

maximum = marks[0]
minimum = marks[0]
total = 0

for mark in marks:
    if mark > maximum:
        maximum = mark

    if mark < minimum:
        minimum = mark

    total = total + mark

average = total / 10

above_average = 0

for mark in marks:
    if mark > average:
        above_average += 1

highest = marks[0]
second_highest = marks[0]

for mark in marks:
    if mark > highest:
        second_highest = highest
        highest = mark
    elif mark > second_highest and mark != highest:
        second_highest = mark

print("Maximum:", maximum)
print("Minimum:", minimum)
print("Average:", average)
print("Students above average:", above_average)
print("Second highest:", second_highest)

Enter 10 marks: 78 65 92 88 45 76 90 55 81 70
Maximum: 92
Minimum: 45
Average: 74.0
Students above average: 6
Second highest: 90


Q38

In [36]:
review = input("Enter a review: ")

words = review.lower().split()

frequency = {}

for word in words:
    if word in frequency:
        frequency[word] += 1
    else:
        frequency[word] = 1

sorted_words = sorted(frequency.items(), key=lambda x: x[1], reverse=True)

print("Word frequencies:")

for word, count in sorted_words:
    print(word, ":", count)

most_frequent = sorted_words[0]

print("Most frequent word:", most_frequent[0])
print("Count:", most_frequent[1])

Enter a review: the place was clean and tidy
Word frequencies:
the : 1
place : 1
was : 1
clean : 1
and : 1
tidy : 1
Most frequent word: the
Count: 1


Q39

In [41]:
states = {
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Kerala": "Thiruvananthapuram",
    "Tamil Nadu": "Chennai",
    "West Bengal": "Kolkata"
}

while True:
    print("\n1. Add a new state")
    print("2. Update an existing capital")
    print("3. Delete a state")
    print("4. Search a state")
    print("5. Display all states")
    print("6. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        state = input("Enter state: ")
        capital = input("Enter capital: ")
        states[state] = capital
        print("State added.")

    elif choice == "2":
        state = input("Enter state: ")

        if state in states:
            capital = input("Enter new capital: ")
            states[state] = capital
            print("Capital updated.")
        else:
            print("State not found.")

    elif choice == "3":
        state = input("Enter state: ")

        if state in states:
            del states[state]
            print("State deleted.")
        else:
            print("State not found.")

    elif choice == "4":
        state = input("Enter state: ")

        if state in states:
            print("Capital:", states[state])
        else:
            print("Not found")

    elif choice == "5":
        for state in sorted(states):
            print(state, ":", states[state])

    elif choice == "6":
        print("Exiting...")
        break

    else:
        print("Invalid choice.")


1. Add a new state
2. Update an existing capital
3. Delete a state
4. Search a state
5. Display all states
6. Exit
Enter your choice: 1
Enter state: kerala
Enter capital: thiruvananthapuram
State added.

1. Add a new state
2. Update an existing capital
3. Delete a state
4. Search a state
5. Display all states
6. Exit
Enter your choice: 6
Exiting...


Q40

In [42]:
section_a = {"Python", "Java", "C++", "SQL"}
section_b = {"Java", "JavaScript", "Python", "Go", "SQL"}

# (a) Languages known by both sections
both = section_a & section_b

# (b) Languages known only by Section A
only_a = section_a - section_b

# (c) Languages known only by Section B
only_b = section_b - section_a

# (d) Total unique languages
all_languages = section_a | section_b

# (e) Languages exclusive to one section
exclusive = section_a ^ section_b

print("Both sections:", both)
print("Only Section A:", only_a)
print("Only Section B:", only_b)
print("Total unique languages:", len(all_languages))
print("Exclusive to one section:", exclusive)

Both sections: {'Java', 'Python', 'SQL'}
Only Section A: {'C++'}
Only Section B: {'JavaScript', 'Go'}
Total unique languages: 6
Exclusive to one section: {'JavaScript', 'C++', 'Go'}


Q41

In [43]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)

days = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

maximum = max(prices)
minimum = min(prices)

max_day = days[prices.index(maximum)]
min_day = days[prices.index(minimum)]

average = sum(prices) / len(prices)

biggest_gain = 0
gain_day = ""

volatility = 0

for i in range(1, len(prices)):
    change = prices[i] - prices[i - 1]

    if change > biggest_gain:
        biggest_gain = change
        gain_day = days[i - 1] + " to " + days[i]

    volatility = volatility + abs(change)

print("Maximum price:", maximum, "on", max_day)
print("Minimum price:", minimum, "on", min_day)
print("Average price:", round(average, 2))
print("Biggest single-day gain:", biggest_gain, "between", gain_day)
print("Total volatility:", volatility)

Maximum price: 4055 on Sun
Minimum price: 3845 on Mon
Average price: 3949.29
Biggest single-day gain: 77 between Wed to Thu
Total volatility: 286


Q42

In [44]:
numbers = [4, 7, 2, 4, 9, 7, 1, 3, 2, 8, 5, 9, 6, 3, 10, 4, 7, 11, 12, 5]

unique_numbers = set(numbers)

repeated = []
exactly_once = []

for number in unique_numbers:
    if numbers.count(number) > 1:
        repeated.append(number)
    else:
        exactly_once.append(number)

print("Unique numbers:", unique_numbers)
print("Numbers appearing more than once:", repeated)
print("Numbers appearing exactly once:", exactly_once)

Unique numbers: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
Numbers appearing more than once: [2, 3, 4, 5, 7, 9]
Numbers appearing exactly once: [1, 6, 8, 10, 11, 12]


Q43

In [45]:
sentence = input("Enter a sentence: ")

cleaned = ""

for char in sentence:
    if char.isalnum():
        cleaned = cleaned + char.lower()

if cleaned == cleaned[::-1]:
    print("TRUE - It is a palindrome")
else:
    print("FALSE - It is not a palindrome")

Enter a sentence: hello world
FALSE - It is not a palindrome


Q44

In [47]:
sentence = input("Enter a sentence: ")

words = sentence.split()
result = ""

for word in words:
    new_word = word[0].upper() + word[1:].lower()
    result = result + new_word + " "

print(result)

Enter a sentence: hello world from kerala
Hello World From Kerala 


  Q45

In [48]:
message = input("Enter a message: ")
shift = int(input("Enter shift value: "))

encrypted = ""

for char in message:
    if char.isupper():
        new_char = chr((ord(char) - ord("A") + shift) % 26 + ord("A"))
        encrypted = encrypted + new_char

    elif char.islower():
        new_char = chr((ord(char) - ord("a") + shift) % 26 + ord("a"))
        encrypted = encrypted + new_char

    else:
        encrypted = encrypted + char

print("Encrypted message:", encrypted)

Enter a message: hello world
Enter shift value: 7
Encrypted message: olssv dvysk


Q46

In [49]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive == False:
        base_amount = amount
        gst_amount = amount * gst_rate / 100
        total_amount = amount + gst_amount

    else:
        total_amount = amount
        base_amount = amount / (1 + gst_rate / 100)
        gst_amount = total_amount - base_amount

    return (round(base_amount, 2), round(gst_amount, 2), round(total_amount, 2))


print(calculate_gst(1000))
print(calculate_gst(1180, gst_inclusive=True))
print(calculate_gst(500, gst_rate=5))

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180)
(500, 25.0, 525.0)


Q47

In [50]:
def power(base, exp):
    if exp == 0:
        return 1

    if exp < 0:
        return 1 / power(base, -exp)

    return base * power(base, exp - 1)


print(power(2, 10))
print(power(5, 0))
print(power(3, -2))

1024
1
0.1111111111111111


Q48

In [51]:
import numpy as np

# (a) Create a 5x5 identity matrix
matrix = np.eye(5)
print("Identity Matrix:")
print(matrix)

# (b) Multiply every element by 10
matrix = matrix * 10
print("\nAfter multiplying by 10:")
print(matrix)

# (c) Transpose the matrix
# The transpose of an identity matrix is itself because its 1s
# are already on the main diagonal.
matrix = matrix.T
print("\nTranspose:")
print(matrix)

# (d) Sum of diagonal elements
diagonal_sum = np.trace(matrix)
print("\nSum of diagonal elements:", diagonal_sum)

# (e) Sum of all elements
total_sum = np.sum(matrix)
print("Sum of all elements:", total_sum)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

After multiplying by 10:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Transpose:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Sum of diagonal elements: 50.0
Sum of all elements: 50.0


Q49

In [52]:
import numpy as np

sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

# (a) Total weekly sales
total_sales = np.sum(sales)

# (b) Daily average
average_sales = np.mean(sales)

# (c) Day with maximum sales
maximum_sales = np.max(sales)
maximum_day = days[np.argmax(sales)]

# (d) Number of days above the weekly average
days_above_average = np.sum(sales > average_sales)

# (e) Percentage growth from Monday to Sunday
growth = ((sales[-1] - sales[0]) / sales[0]) * 100

# (f) Day-on-day percentage changes
daily_changes = ((sales[1:] - sales[:-1]) / sales[:-1]) * 100

print("Total weekly sales:", total_sales)
print("Daily average:", round(average_sales, 2))
print("Maximum sales:", maximum_sales, "on", maximum_day)
print("Days above average:", days_above_average)
print("Monday to Sunday growth:", round(growth, 2), "%")
print("Day-on-day % changes:", np.round(daily_changes, 2))

Total weekly sales: 150200
Daily average: 21457.14
Maximum sales: 35200 on Sat
Days above average: 3
Monday to Sunday growth: 136.67 %
Day-on-day % changes: [ 54.17 -23.24  55.63 -10.41  77.78 -19.32]


Q50

In [53]:
import numpy as np

matrix = np.ones((5, 5), dtype=int)

matrix[1:4, 1:4] = 0

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
